### PR TITLE
add union_distinct

### PR DESCRIPTION
**Pull request by andyleclair**
ClickHouse supports `UNION DISTINCT` and it would be cool if this library did too

https://clickhouse.com/docs/en/sql-reference/statements/select/union

### CODE REVIEW

**Comment by ruslandoga** [comment]
👋 @andyleclair 

Thank you for the PR. I think we should check with Ecto team if that's a safe approach.

**Comment by ruslandoga** [comment]
Actually, aren't `UNION` and `UNION DISTINCT` the same thing?

**Comment by jojoca-appcues** [comment]
They're supposed to be the same but clickhouse forces you to specify whether it's a distinct or all operation. In certain cases, the queries fail if you don't specify the union strategy.

**Comment by ruslandoga** [comment]
👋 @jojoca-appcues 

Can you please provide more information? Do you mean this situation:

```sql
:) select * from values(1) union select * from values(2);
-- Received exception from server (version 24.3.3):
-- Code: 558. DB::Exception: Received from localhost:9000. DB::Exception: Expected ALL or DISTINCT in SelectWithUnion query, because setting (union_default_mode) is empty: While processing SELECT * FROM values(1) UNION SELECT * FROM values(2). (EXPECTED_ALL_OR_DISTINCT)
```
In that case, instead of adding `union_distinct`, shouldn't we change the SQL generated for `union` to be `UNION DISTINCT` instead of just `UNION`?

**Comment by jojoca-appcues** [comment]
Exactly that error! 
I agree changing UNION with UNION DISTINCT would do the trick

**Comment by ruslandoga** [comment]
Also we can do this (already):

```elixir
Repo.query("select * from values(1) union select * from values(2)", [], settings: [union_default_mode: "DISTINCT"])
```

**Comment by jojoca-appcues** [comment]
Ah this is cool! I'll try it here 😃

**Comment by andyleclair** [comment]
I support changing `union` to return `UNION DISTINCT`. The default behavior of erroring if you don't pass the `union_default_mode` is a little annoying. I'm happy to make that change if you want, then we can drop the `Builder` call

**Comment by ruslandoga** [comment]
@andyleclair thank you! Let's do this!

**Review by ruslandoga — APPROVED** [review]
Thank you!

**Comment by ruslandoga** [comment]
I'll publish a new version later today.

**Comment by ruslandoga** [comment]
Published as v0.4.0.

Thank you @andyleclair @jojoca-appcues!

**Pull request merged**
